nelmio_security:
    signed_cookie:
        names: []

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # prevents redirections outside the website's domain
    external_redirects:
        abort: true
        log: true

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    forced_ssl:
        hsts_max_age: 31536000 # 1 year
        hsts_subdomains: true
        hsts_preload: true

    csp:
        compat_headers: false
        report_endpoint:
            log_channel: security
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src:
                - 'none'
            base-uri:
                - 'none'
            script-src:
                - 'self'
            img-src:
                - 'self'
                - 'data:'
            style-src:
                - 'self'
            connect-src:
                - 'self'
            form-action:
                - 'self'
            font-src:
                - 'self'
            block-all-mixed-content: true
            upgrade-insecure-requests: true

when@dev:
    nelmio_security:
        forced_ssl:
            enabled: false
        csp:
            enforce:
                script-src:
                    - 'https://localhost:8080'
                    - 'unsafe-inline'
                img-src:
                    - 'https://localhost:8080'
                style-src:
                    - 'https://localhost:8080'
                    - 'unsafe-inline'
                connect-src:
                    - 'wss://localhost:8080'
                    - 'https://localhost:8080'
                font-src:
                    - 'https://localhost:8080'
