version: "3.4"

services:
  app:
    image: ${IMAGE:-app}:${CI_COMMIT_SHORT_SHA:-main}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: symfony_php_serve
      cache_from:
        - ${CI_IMAGE:-app}:main
        - ${IMAGE:-app}:main
        - ${IMAGE:-app}:${CI_COMMIT_REF_SLUG:-main}
      args:
        BUILDKIT_INLINE_CACHE: 1
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    depends_on:
      - database
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    image: ${IMAGE:-www}:${CI_COMMIT_SHORT_SHA:-main}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: symfony_caddy
      cache_from:
        - ${CI_IMAGE:-www}:main
        - ${IMAGE:-www}:main
        - ${IMAGE:-www}:${CI_COMMIT_REF_SLUG:-main}
      args:
          BUILDKIT_INLINE_CACHE: 1
    depends_on:
      - app
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.6.7
    environment:
      MARIADB_DATABASE: app
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_USER: symfony
      MARIADB_PASSWORD: ChangeMe
    volumes:
      - db-data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
  php_socket:
  caddy_data:
  caddy_config:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
