apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ../../base
    - ingress.yaml

patchesStrategicMerge:
    - environment_app.yaml

namePrefix: ????-production-
commonLabels:
    environment: production
