services:

    App\Security\SamlBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    App\Security\SamlBundle\Controller\SamlController:
        arguments:
            - '@logger'
            - '@surfnet_saml.metadata_factory'
            - '@surfnet_saml.http.post_binding'
            - '@surfnet_saml.remote.idp'
            - '@surfnet_saml.hosted.service_provider'
        tags:
            - controller.service_arguments
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

    # Firewall
    surfnet_saml.saml_provider:
        class: App\Security\SamlBundle\Authentication\SamlProvider

    App\Security\SamlBundle\Authentication\SamlProvider:
        alias: surfnet_saml.saml_provider
